-- =========================================================
-- Coffee Lab Database (PostgreSQL)
-- Purpose: A small but relational dataset for Labs (incl. Lab 9: users/privileges/views)
-- Author: Generated by ChatGPT
-- =========================================================

-- Recommended: run as superuser or a role with CREATEDB/CREATEROLE privileges.

-- 0) (Optional) Create database
-- CREATE DATABASE coffee_lab WITH ENCODING='UTF8';
-- \c coffee_lab

-- 1) Clean up (safe for re-run)
DROP SCHEMA IF EXISTS coffee CASCADE;
CREATE SCHEMA coffee;

-- 2) Core tables
CREATE TABLE coffee.customer (
  customer_id  BIGSERIAL PRIMARY KEY,
  full_name    VARCHAR(120) NOT NULL,
  phone        VARCHAR(30),
  email        VARCHAR(120) UNIQUE,
  member_since DATE DEFAULT CURRENT_DATE
);

CREATE TABLE coffee.employee (
  employee_id BIGSERIAL PRIMARY KEY,
  full_name   VARCHAR(120) NOT NULL,
  position    VARCHAR(60) NOT NULL, -- e.g., Barista, Cashier, Manager
  hire_date   DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE coffee.category (
  category_id BIGSERIAL PRIMARY KEY,
  category_name VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE coffee.product (
  product_id   BIGSERIAL PRIMARY KEY,
  category_id  BIGINT NOT NULL REFERENCES coffee.category(category_id),
  product_name VARCHAR(120) NOT NULL,
  price        NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE(category_id, product_name)
);

CREATE TABLE coffee."order" (
  order_id     BIGSERIAL PRIMARY KEY,
  order_ts     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  customer_id  BIGINT REFERENCES coffee.customer(customer_id),
  employee_id  BIGINT NOT NULL REFERENCES coffee.employee(employee_id),
  status       VARCHAR(20) NOT NULL DEFAULT 'PAID' CHECK (status IN ('PENDING','PAID','CANCELLED')),
  note         TEXT
);

CREATE TABLE coffee.order_item (
  order_item_id BIGSERIAL PRIMARY KEY,
  order_id      BIGINT NOT NULL REFERENCES coffee."order"(order_id) ON DELETE CASCADE,
  product_id    BIGINT NOT NULL REFERENCES coffee.product(product_id),
  qty           INTEGER NOT NULL CHECK (qty > 0),
  unit_price    NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
  discount      NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (discount >= 0)
);

CREATE TABLE coffee.payment (
  payment_id BIGSERIAL PRIMARY KEY,
  order_id   BIGINT NOT NULL UNIQUE REFERENCES coffee."order"(order_id) ON DELETE CASCADE,
  method     VARCHAR(20) NOT NULL CHECK (method IN ('CASH','CARD','TRANSFER','QR')),
  amount     NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
  paid_ts    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3) Helpful indexes
CREATE INDEX idx_order_ts ON coffee."order"(order_ts);
CREATE INDEX idx_order_customer ON coffee."order"(customer_id);
CREATE INDEX idx_order_employee ON coffee."order"(employee_id);
CREATE INDEX idx_item_order ON coffee.order_item(order_id);
CREATE INDEX idx_item_product ON coffee.order_item(product_id);

-- 4) Seed data (small dataset)
INSERT INTO coffee.category(category_name) VALUES
 ('Coffee'), ('Tea'), ('Bakery'), ('Non-Coffee');

INSERT INTO coffee.product(category_id, product_name, price) VALUES
 ((SELECT category_id FROM coffee.category WHERE category_name='Coffee'), 'Americano', 55.00),
 ((SELECT category_id FROM coffee.category WHERE category_name='Coffee'), 'Latte', 65.00),
 ((SELECT category_id FROM coffee.category WHERE category_name='Coffee'), 'Cappuccino', 65.00),
 ((SELECT category_id FROM coffee.category WHERE category_name='Tea'), 'Thai Milk Tea', 60.00),
 ((SELECT category_id FROM coffee.category WHERE category_name='Tea'), 'Green Tea', 60.00),
 ((SELECT category_id FROM coffee.category WHERE category_name='Bakery'), 'Croissant', 45.00),
 ((SELECT category_id FROM coffee.category WHERE category_name='Bakery'), 'Chocolate Muffin', 50.00),
 ((SELECT category_id FROM coffee.category WHERE category_name='Non-Coffee'), 'Cocoa', 65.00);

INSERT INTO coffee.customer(full_name, phone, email, member_since) VALUES
 ('Somchai Prasert', '081-000-1111', 'somchai@example.com', '2025-06-01'),
 ('Suda Wong',       '089-222-3333', 'suda@example.com',    '2025-08-15'),
 ('Anan K.',         '086-444-5555', 'anan@example.com',    '2025-12-20'),
 ('Guest Customer',  NULL,           NULL,                 CURRENT_DATE);

INSERT INTO coffee.employee(full_name, position, hire_date) VALUES
 ('Nicha R.', 'Cashier', '2025-01-10'),
 ('Poom S.',  'Barista', '2025-02-01'),
 ('Mali P.',  'Manager', '2024-10-01');

-- 5) Sample orders (deterministic set)
-- Order 1
INSERT INTO coffee."order"(order_ts, customer_id, employee_id, status, note)
VALUES ('2026-02-15 09:05:00',
        (SELECT customer_id FROM coffee.customer WHERE full_name='Somchai Prasert'),
        (SELECT employee_id FROM coffee.employee WHERE full_name='Nicha R.'),
        'PAID',
        'Morning coffee');

INSERT INTO coffee.order_item(order_id, product_id, qty, unit_price, discount)
VALUES
 (1, (SELECT product_id FROM coffee.product WHERE product_name='Americano'), 1, 55.00, 0),
 (1, (SELECT product_id FROM coffee.product WHERE product_name='Croissant'), 1, 45.00, 5.00);

INSERT INTO coffee.payment(order_id, method, amount, paid_ts)
VALUES (1, 'CASH', 95.00, '2026-02-15 09:06:00');

-- Order 2
INSERT INTO coffee."order"(order_ts, customer_id, employee_id, status, note)
VALUES ('2026-02-15 13:20:00',
        (SELECT customer_id FROM coffee.customer WHERE full_name='Suda Wong'),
        (SELECT employee_id FROM coffee.employee WHERE full_name='Nicha R.'),
        'PAID',
        NULL);

INSERT INTO coffee.order_item(order_id, product_id, qty, unit_price, discount)
VALUES
 (2, (SELECT product_id FROM coffee.product WHERE product_name='Latte'), 2, 65.00, 0),
 (2, (SELECT product_id FROM coffee.product WHERE product_name='Chocolate Muffin'), 1, 50.00, 0);

INSERT INTO coffee.payment(order_id, method, amount, paid_ts)
VALUES (2, 'QR', 180.00, '2026-02-15 13:21:00');

-- Order 3 (next day)
INSERT INTO coffee."order"(order_ts, customer_id, employee_id, status, note)
VALUES ('2026-02-16 10:10:00',
        (SELECT customer_id FROM coffee.customer WHERE full_name='Guest Customer'),
        (SELECT employee_id FROM coffee.employee WHERE full_name='Nicha R.'),
        'PAID',
        'Guest');

INSERT INTO coffee.order_item(order_id, product_id, qty, unit_price, discount)
VALUES
 (3, (SELECT product_id FROM coffee.product WHERE product_name='Thai Milk Tea'), 1, 60.00, 0),
 (3, (SELECT product_id FROM coffee.product WHERE product_name='Cocoa'), 1, 65.00, 0);

INSERT INTO coffee.payment(order_id, method, amount, paid_ts)
VALUES (3, 'CARD', 125.00, '2026-02-16 10:11:00');

-- Order 4 (cancelled example)
INSERT INTO coffee."order"(order_ts, customer_id, employee_id, status, note)
VALUES ('2026-02-16 15:40:00',
        (SELECT customer_id FROM coffee.customer WHERE full_name='Anan K.'),
        (SELECT employee_id FROM coffee.employee WHERE full_name='Nicha R.'),
        'CANCELLED',
        'Customer changed mind');

INSERT INTO coffee.order_item(order_id, product_id, qty, unit_price, discount)
VALUES
 (4, (SELECT product_id FROM coffee.product WHERE product_name='Cappuccino'), 1, 65.00, 0);

-- (No payment for cancelled)

-- 6) Views used in labs (read-only reporting)
CREATE OR REPLACE VIEW coffee.v_order_summary AS
SELECT
  o.order_id,
  o.order_ts,
  o.status,
  COALESCE(c.full_name, 'Guest') AS customer_name,
  e.full_name AS cashier_name,
  SUM(oi.qty * oi.unit_price - oi.discount) AS gross_amount
FROM coffee."order" o
LEFT JOIN coffee.customer c ON c.customer_id = o.customer_id
JOIN coffee.employee e ON e.employee_id = o.employee_id
JOIN coffee.order_item oi ON oi.order_id = o.order_id
GROUP BY o.order_id, o.order_ts, o.status, COALESCE(c.full_name, 'Guest'), e.full_name;

CREATE OR REPLACE VIEW coffee.v_daily_sales AS
SELECT
  DATE(o.order_ts) AS sales_date,
  COUNT(DISTINCT o.order_id) FILTER (WHERE o.status='PAID') AS paid_orders,
  SUM(oi.qty * oi.unit_price - oi.discount) FILTER (WHERE o.status='PAID') AS paid_revenue
FROM coffee."order" o
JOIN coffee.order_item oi ON oi.order_id = o.order_id
GROUP BY DATE(o.order_ts)
ORDER BY sales_date;

-- 7) Sanity checks (optional)
-- SELECT * FROM coffee.v_order_summary ORDER BY order_id;
-- SELECT * FROM coffee.v_daily_sales;
SELECT current_database(), current_user, session_user;

create user testcoffee with password 'testcoffee123' ;
create user u_cashier with password 'cashier123' ; 


alter role testcoffee login password 'testcoffee123' ;

alter role U_cashier login password 'cashier123' ; 

SELECT rolname, rolcanlogin FROM pg_roles WHERE rolname IN ('testcoffee','u_cashier');

GRANT CONNECT ON DATABASE lab08 TO testcoffee, u_cashier;
GRANT USAGE  ON SCHEMA coffee TO testcoffee, u_cashier;

INSERT INTO coffee.category(category_name) VALUES ('ShouldFail');
